export const ADD_TODO = 'ADD_TODO';
export const UPDATE_DEVELOPER_FIELD = 'UPDATE_DEVELOPER_FIELD';
export const UPDATE_PROJECT_FIELD = 'UPDATE_PROJECT_FIELD';
export const DELETE_ITEM = 'DELETE_ITEM';
